import assert from 'node:assert/strict';
import { PitchScore } from '../src/trainer/score.mjs';
const score = new PitchScore();
assert.equal(score.update(0), null);
assert.equal(score.update(0, 0).score, 100);
score.reset();
score.update(0, 50);
let result = score.update(1000, 50);
assert.equal(result.deviation, 0);
assert.equal(result.rms, 50);
assert.ok(result.score < 100, 'Steady off-target singing must not receive a perfect score');
score.reset();
score.update(0, -10); result = score.update(1000, 10);
assert.equal(result.deviation, 10); assert.equal(result.rms, 10);
result = score.update(2000);
assert.equal(result.deviation, 0); assert.equal(result.rms, 10);
assert.equal(score.update(3000), null, 'Silence ages out all samples');
score.update(4000, 30); score.reset(); assert.equal(score.update(4001), null);
console.log('Score checks passed: accuracy, stability, rolling expiry, silence and reset.');
